apiVersion: v1
kind: Secret
metadata:
  name: dai-enduro-secret
type: Opaque
stringData:
  dai-enduro-worker.toml: |
    debug = true
    verbosity = 2

    [temporal]
    address = "temporal-frontend.enduro-sdps:7233"
    namespace = "default"

    [worker]
    taskQueue = "preprocessing"
    maxConcurrentSessions = 1

    [preprocessing]
    workflowName = "preprocessing"
    sharedPath = "/home/enduro/preprocessing"

    [preprocessing.bagCreate]
    checksumAlgorithm = "sha512"
